### PR TITLE
[4.x] Fixed broken code and tests

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by nunomaduro** [comment]
Hey @GrahamCampbell, 

Do you plan to merge those changes on the `stable` branch? Because the `4.x` branch will be deprecated once Laravel 8 is out.

**Comment by GrahamCampbell** [comment]
4.x is the branch for Laravel 7, which is still supported for 3 more months, with security fixes for 15 more months, so I think it's important these fixes are merged into 4.x.

If you don't want to apply any fixes to 4.x, then also my other PR to address the .env issues should also be closed.

**Comment by GrahamCampbell** [comment]
I was assuming you'd merge 4.x -> stable upwards after this PR was merged into 4.x?

**Comment by GrahamCampbell** [comment]
I could probably PR a 4.x -> stable merge, if that would be helpful.

**Comment by nunomaduro** [comment]
@GrahamCampbell I see - honestly, and if you are ok with it, I would prefer just perform changes on the `stable` branch that contains Collision 5 ( for Laravel 8 ). And for the moment, do not ship any changes on the `4.x`. The code there is quite stable, and no bugs have been found so far.

And also, the `stable` branch already contains your work on supporting correctly `dotenv` 5: https://github.com/nunomaduro/collision/commit/95b928bf87a9ee4a023455a52a63cb4d1afeec0a.

Still, some of the changes you made in this branch may make sense on the `stable` branch. Let me know what do you think.

**Comment by GrahamCampbell** [comment]
> and no bugs have been found so far.

Apart from the issues with the .env file loading?

**Comment by GrahamCampbell** [comment]
And there's a fatal error due to a class not found fix in this PR.

**Comment by nunomaduro** [comment]
> Apart from the issues with the .env file loading?

Correct, but again, let me know if you think there are **real world** problems on not having this changes on the `v4.x`.

> And there's a fatal error due to a class not found fix in this PR.

Nice catch! Problem probably got introduced here: https://github.com/nunomaduro/collision/commit/9b430e44467e7186f5a7e48c8cdeac0571817286. For some reason, phpstan did'nt complain about it at the time. This bugfix should be ported to the `stable` branch.

**Comment by GrahamCampbell** [comment]
I'll prepare a new version of this PR for the stable branch, then. I'll let you know when I have it ready. I'm currently working on PHP 8 support for Mockery 1.3, which is taking **ages**, so probably not today. 😆

**Comment by nunomaduro** [comment]
Thank you so much @GrahamCampbell! Sure, take your time. 👍

**Pull request closed without merging**
