### PR TITLE
Adds syntax highlighting

### PR DESCRIPTION
**Pull request by felixdorn**
This PR adds true syntax highlighting to Collision. Currently, only keywords and some tokens (`(`, `)`, `->`, etc) are highlighted. If this PR is merged, proper IDE-like syntax highlighting will be rendered.

### Before
image
### After
image

Collision would rely on a new dependency [`tin`](https://github.com/felixdorn/tin), which itself has no dependencies and is PHP 8.2 ready.

Another benefit is, because `tin` handles lines in a more complex way, it would remove a trailing empty line, making the output more concise.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you explain a little bit more the advantages of that package?

**Comment by owenvoke** [comment]
I quite like the current implementation, but that's just me. 🤷🏻 It already almost has syntax highlighting (or at least... allows you to easily see between certain types like strings).

I'm interested what you mean about the trailing empty line, as I can't see any line difference between the outputs. 🤔

**Comment by felixdorn** [comment]
Here's a comparison of what gets highlighted  currently and using the code from this PR:
| Features         | Current          | This PR              |
|------------------|------------------|----------------------|
| Keywords         | ✅                | ✅                    |
| Constants        |-                  | ✅                     |
| User-defined constants        |-                  | ✅                     |
| Variables        |-                  | ✅                    |
| Inline HTML      | ✅                | ✅                    |
| Strings      | ✅                | ✅                    |
| Comments      | ✅                | ✅                    |
| Class Names      |-                  | ✅                    |
| Function names   |-                  | ✅                    |
| Method names     |-                  | ✅                    |
| Built-in types   |-                  | ✅                    |
| Attributes       |-                  | ✅                    |
| Named parameters |-                  | ✅                    |
| Enums            |-                  | ✅                    |


## Why "true" syntax highlighting matters?
Code is easier to scan at a glance, leading to less time spent understanding the context of a given error. 

## Why a package?
My first attempt at adding "true" syntax highlighting was done directly in Collision but it has a few drawbacks:

It would add a lot of code directly in Collision's core. While the amount of code could be somewhat reduced, this would result in long hard-to-read code. 
I would still have to  maintain tin and help maintaining Collision's Highlighter. That means porting new features to a different, trimmed version of tin, this process would be time-consuming and error-prone.
If the code is ported as-is in Collision, there would be a lot of unused code and the maintaining problem remains.

@owenvoke If the highlighted snippet ends with empty lines, it removes them: see https://github.com/nunomaduro/collision/pull/233/files#diff-5dafb89713bb868a409baf72a2831d8ee45963cae3384f29838a1ffecf6533ec

**Comment by felixdorn** [comment]
Here's a better preview of the syntax highlighter: 
image
Or with another theme:
image

**Comment by owenvoke** [comment]
@felixdorn, ah, I see what you mean. Guess there weren't any trailing linebreaks in the initial screenshot so I wasn't sure if that's what you were meaning. 👍🏻

**Comment by nunomaduro** [comment]
Putting this on hold.

**Pull request closed without merging**
