### PR TITLE
Adds Silex adapter 🔥

### PR DESCRIPTION
**Pull request by daidais**
Add adapter for Pimple and Silex

### CODE REVIEW

**Comment by nunomaduro** [comment]
Hey @daidais! Thanks again for this PR!

Tell me, what is missing to make adapter available for Silex? 🙂

**Comment by daidais** [comment]
@nunomaduro It miss nothing but I was asking myself if my implementation don't miss something you write in collision to wrap the `Whoops\Run`.
But I have test it and it works ;)

**Comment by nunomaduro** [comment]
@daidais Great! I probably don't have time this month to review this! But will be the first thing todo on the month of December! 😘

**Comment by nunomaduro** [comment]
@daidais Unfortunately the development of Silex have finished. And the security and bus fixes will finished this year. 

Source: http://symfony.com/blog/the-end-of-silex

I am super interested in a symfony 4 adapter tho. The code chance that much? 😕

**Comment by nunomaduro** [comment]
@daidais Thanks for your work. But since the development of Silex have finished I don't want to maintain an adapter of Silex.

I am completely open for other adapters tho! Good job.

**Pull request closed without merging**
