### PR TITLE
PHP dotenv fixes for Laravel 7

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by nunomaduro** [comment]
@GrahamCampbell Thanks for wanted to help here. A few questions before:

1. What is the problems this pull request solves?
2. There is any breaking possible breaking change for our users? environment variables that existed before and not now? Can tests suites fail because they were relying on the previous behaviour?
3. Are you confident on the changes of this pull request?

**Comment by GrahamCampbell** [comment]
The problem was explained at: https://github.com/nunomaduro/collision/pull/125#discussion_r442509020. Many users probably never noticed this bug, but when we changed the behaviour in the framework core, lots of people noticed (and we changed it back). It is important the .env file variables are only loaded if they are not already present in the environment, and the same for clearing them, which is why the original implementation was incorrect.

The other benefit to this PR is that of performance. We skip straight to clearing the variables, rather than loading them first. Doing this is cleaner in v5, but it is still possible in v4, as in this PR.

**Comment by GrahamCampbell** [comment]
The old code was also not respecting if getenv/putenv support was enabled or not.

**Comment by nunomaduro** [comment]
@GrahamCampbell Thanks for explaining. 

Going to test a little bit locally before merge.

**Comment by nunomaduro** [comment]
@GrahamCampbell Seems that when `.env.testing` exists, this new code still uses the file `.env`.

**Comment by GrahamCampbell** [comment]
And so does the old code? They both get the env file name from the same place.

**Comment by nunomaduro** [comment]
@GrahamCampbell nop. The old code don't use `.env` if a `.env.testing` is present.

**Comment by GrahamCampbell** [comment]
How did it do that? I've not changed the code that gets the filename to use.

**Comment by GrahamCampbell** [comment]
Perhaps the old code appeared to delete those variables because of the bug where it was clearing env variables that were never loaded by dotenv?

**Comment by nunomaduro** [comment]
Not sure. Going to add some integration tests on the current code in both Collision 4 and 5, so you can rework you current pull request with confidence. 👍

**Comment by nunomaduro** [comment]
Just added some integration tests on the `stable`: https://github.com/nunomaduro/collision/pull/128#issuecomment-647183160. Let's address that pull request first.

**Comment by GrahamCampbell** [comment]
I think the tests are currently asserting that a bug occurs? Either that, or the comments in the code are wrong, and we also want to clear environment variables that were not actually loaded from the dotenv. The variable named `VAR_OVERRIDDEN_IN_PHPUNIT` is not actually overridden. What happens is the variable from the dotenv file with that name is never loaded at all. So, clearing that variable should not unset it.

**Comment by nunomaduro** [comment]
@GrahamCampbell I am appreciate the what you are trying todo, but I am having troubles understand what is the actually bug here. If you have some free time, can you adjust to current tests to the behaviour you think this should have? Just to be the same page:

The tests I've added today are running both `EnvironmentTest` and `EnvironmentTestingTest` on the fake Laravel app with the command `phpunit` [L16](https://github.com/nunomaduro/collision/blob/d05b4f7dfd2cdf963832f9a55865448ef0478f6a/tests/Unit/Adapters/ArtisanTestCommandTest.php#L16) and `artisan test` [L24](https://github.com/nunomaduro/collision/blob/d05b4f7dfd2cdf963832f9a55865448ef0478f6a/tests/Unit/Adapters/ArtisanTestCommandTest.php#L24). And the goal is to make sure that the `ENVs` contains the exactly same values.

I am also available for a zoom/meet call tomorrow if you are up to it!

Concerning `The variable named VAR_OVERRIDDEN_IN_PHPUNIT`. Got it, you mean that because PHPUnit loads those envs, dotenv don't actually override them.

Really thanks for trying to help.

**Comment by GrahamCampbell** [comment]
I'll take a proper look at this next weekend. It would be helpful to have those new tests on the 4.x branch, since that's what this PR is targetting. :)

**Comment by nunomaduro** [comment]
@GrahamCampbell Meanwhile I will try to understand things on my own. 👍

**Comment by GrahamCampbell** [comment]
Before I can start on this, 4.x needs to be in a working state. https://github.com/nunomaduro/collision/pull/134 should address that. After that PR is merged, there will need to be a 4.x->stable merge to take place so the v5 branch gets the same fixes.

**Pull request closed without merging**
