### PR TITLE
Update Printer.php

### PR DESCRIPTION
**Pull request by winkcler**
I added this line so that each test is shown at run time on the console.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@winkcler Can you add screenshots, a video, and update tests?

**Comment by winkcler** [comment]
As you can see below, the tests are being run and are already being shown at run time on the console.
I believe that this way is visibly better, because the user will already know if a test fails.

ezgif com-gif-maker

**Comment by nunomaduro** [comment]
What happens if a test fails? You still see the "PASS" on top?

**Comment by winkcler** [comment]
He keeps running, but he already shows me what he failed in execution time. Something that I could only see at the end of all the tests.

**Comment by winkcler** [comment]
****

**Pull request closed without merging**
