### PR TITLE
add support to phpunit 7

### PR DESCRIPTION
**Pull request by ianrodrigues**
This PR allows Collision supports PHPUnit 7+. For this reason, it also needs a major version update since it doesn't support PHPUnit 6 anymore.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@ianrodrigues Thanks a lot! I will take a look at this just after the release of Laravel 5.6.

**Comment by ianrodrigues** [comment]
@nunomaduro Sure, thank you!

**Comment by DariusIII** [comment]
You should fix it before Laravel 5.6 release, as it will cause problems with testing. As you know Laravel 5.6 includes collision and phpunit 7 "out of the box ".

**Comment by nunomaduro** [comment]
@DariusIII Laravel 5.6 includes only the Laravel Adapter. Not the Phpunit adapter.

**Comment by DariusIII** [comment]
@nunomaduro They pull in the whole collision package. So if the error is there, it will show up regardless of used part. Btw, error is generated by collision itself when trying to run anything from cli.

**Comment by nunomaduro** [comment]
@DariusIII There are two adapters on Collision. Laravel only uses the Laravel adapter, that works *only* for artisan commands.

The phpunit stuff is not used on Laravel 5.6.

See for yourself: `composer create-project laravel/laravel="dev-develop" laravel-5.6 --prefer-dist`

**Comment by nunomaduro** [comment]
@DariusIII Sorry, I still didn't understand you point of view. Give me a clear example.

**Comment by DariusIII** [comment]
@nunomaduro Laravel uses laravel/framework right?

Laravel framework uses phpunit for its tests, currently version 6. 

When 5.6 comes out, it will use phpunit 7,

https://github.com/laravel/framework/blob/5.6/composer.json#L81

https://github.com/laravel/framework/blob/5.6/.travis.yml#L37

 which will then fail because of collision package used in Laravel.

I hope this is a better explanation.

**Comment by nunomaduro** [comment]
@DariusIII But phpunit **is not** required by Collision.

**Comment by DariusIII** [comment]
@nunomaduro But you include phpunit adapter that extends phpunit and fails with phpunit 7, that is the whole point.

**Comment by nunomaduro** [comment]
@DariusIII Sure, but the phpunit adapter **is not** used on laravel 5.6 default applications. Do you mind of outputting the error that you have having please?

**Comment by phh** [comment]
Getting this error when running [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) `artisan ide-helper:meta`:

```
PHP Fatal error:  Declaration of NunoMaduro\Collision\Adapters\Phpunit\Listener::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in /home/vagrant/code/vendor/nunomaduro/collision/src/Adapters/Phpunit/Listener.php on line 33
```

I believe that the return type `:void` is missing from `addError()`

**Comment by phh** [comment]
And can confirm that [1.1.22](https://github.com/nunomaduro/collision/releases/tag/v1.1.22) fixes this. Thanks!

**Comment by nunomaduro** [comment]
@DariusIIl The patch 1.1.22 also fixes your issue?

**Comment by DariusIII** [comment]
@nunomaduro Unfortunately hotfix does not fix it for me, i am getting the following 

> Class "NunoMaduro\Collision\Adapters\Phpunit\Listener" does not exist

**Comment by sixlive** [comment]
@DariusIII I'm a little confused here. All tests pass on the `laravel/framework@5.6` branch as well as stock (example) tests shipped with a generated version of `laravel/framework `using the 5.6 branch.

I also put together a command inside a Laravel 5.6 app to test the functionality of Collision in commands and collision works as expected..

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ThrowError extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tmp:throw-error';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Throws an error for testing collision';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        throw new \Exception('Does it blend?');
    }
}
```

If anything this _might_ break tests for this packages development. Can you provide any specific errors or a secnerio/code that will break? Being that 5.6 will ship today I would like to make sure we fix any issues ASAP.

**Comment by DariusIII** [comment]
@sixlive Laravel/framework passes phpunit tests because it does not use collision. 
Problem will begin when someone creates a laravel/laravel project which has collision included and tries to test anything using phpunit. 

Problem lies within your Listener class as it is not "aligned" with phpunit 7 as pointed out in the issue opened, so when using phpunit we are getting errors.

You can try and run 

`./vendor/bin/phpunit`

**Comment by sixlive** [comment]
@DariusIII correct, I didn't expect there to be an issue with `laravel/framework`, just wanted to cover that base.

I created a new project with `laravel/laravel` on `5.6` and the example tests that ship with the framework (2) pass, am I missing something?

**Comment by sixlive** [comment]
There ARE issues however if you attempt to use the PHPUnit adaptor, but that doesn't ship with `5.6` and you would have to manually add that to the `phpunit.xml`

e.g. https://github.com/nunomaduro/collision/blob/stable/README.md#phpunit-adapter

**Comment by DariusIII** [comment]
Ah, i remembered when you mentioned it, that i, indeed, have added those lines to my phpunit.xml.

I am sorry if i have created a confusion. Will remove that for time being.

**Comment by sebastiaanluca** [comment]
Original issue was solved, but having the same "Class "NunoMaduro\Collision\Adapters\Phpunit\Listener" does not exist" problem now. Removing that line from `phpunit.xml` fixes it.

The readme still contains this instruction, which results in a problem. Should a new issue be created for this or is it part of the upgrade to PHPUnit 7?

**Comment by nunomaduro** [comment]
@ianrodrigues This PR is already merged on Collision v2. Should come out before the end of this month.

**Comment by ianrodrigues** [comment]
Nice! Thank you, man!

**Pull request merged**
