### PR TITLE
Switch every test case icons to semantic symbols

### PR DESCRIPTION
**Pull request by alexmartinfr**
Every status icon is now using a semantic symbol to allow for quick scanning and visual cohesion:

- RISKY & WARN both use `!` (reasoning: PHPUnit provides an explanation of the error to understand what's going on.)
- INCOMPLETE uses `…` (reasoning: an ellipsis indicates an intentional omission of something. Here, a test.)
- SKIPPED uses `-` (reasoning : run the suite, "minus" this test)

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks for the proposal. Putting this on hold. I am not sure about this changes.

**Comment by alexmartinfr** [comment]
I stumbled upon this package for PHPUnit which adopts a similar principle, but not the exact same symbols:

[https://github.com/mikeerickson/phpunit-pretty-result-printer](https://github.com/mikeerickson/phpunit-pretty-result-printer)

I'll check if there are other similar popular packages to see if there is an emerging trend/convention.

**Comment by nunomaduro** [comment]
Can you show some prints,

**Comment by alexmartinfr** [comment]
They render tests on an horizontal line:

image

Also, they have a `phpunit-printer.yml` configuration file to configure custom markers (but I prefer good defaults to configuration):

Capture d’écran 2020-06-17 à 01 44 02

**Comment by nunomaduro** [comment]
Can you show some prints how it would look like in ours with the new icons?

**Comment by alexmartinfr** [comment]
Oh yeah, I was sure I did that.
Here is what it would look like with this PR:

New Collision Symbols


And here is what it would look like on a more real-life test suite:

Pest with the new Symbols

**Comment by nunomaduro** [comment]
Great. Looks good to me. Can this be merged?

**Comment by alexmartinfr** [comment]
Yes 👍

**Pull request merged**
