### PR TITLE
Fix loading APP_ENV specific .env files

### PR DESCRIPTION
**Pull request by Wyox**
When running `php artisan test` environment specific .env files aren't loaded.

Creating a fresh Laravel installation comes with a phpunit.xml file where `APP_ENV=testing` is defined. When running `phpunit` it would load a .env.testing file if it exists in the project root and include those variables when testing.

This should fix and mimic the same way as Laravel loads environment specific .env files when running `php artisan test`

### CODE REVIEW

**Comment by nunomaduro** [comment]
I don't get the problem from your description. Can you explain again? Also, can you give me a piece of code that works running the normal `phpunit` and doesn't work running `artisan test`?

**Comment by Wyox** [comment]
Environment specific .env files aren't loaded when running `php artisan test`. If you would set APP_ENV=testing in phpunit.xml and run phpunit, laravel would load .env.testing when you run any tests. When running `php artisan test` it doesn't load these.

I created an example here: https://github.com/Wyox/laravel-artisan-test-env

This is a fresh project created by doing the following

```bash
laravel new .
cp .env.example .env
cp .env.example .env.testing
# Modify APP_NAME=Laravel to APP_NAME=Testing
sed -i -e "s/APP_NAME=Laravel/APP_NAME=Testing/g" ".env.testing"
```
Add the following testcase: https://github.com/Wyox/laravel-artisan-test-env/blob/master/tests/Feature/EnvironmentTest.php

The TestCase validates if the correct APP_NAME is loaded based on a given APP_ENV

Run the following:
```
# Passes
./vendor/bin/phpunit

# Fails
php artisan test 
```

If I apply the changes as described in the PR both `php artisan test` and `phpunit` pass the test

**Comment by nunomaduro** [comment]
Screenshot 2020-03-05 at 14 55 37

**Comment by nunomaduro** [comment]
Seems everything is good in my side, can you share more details? OS used, etc.

**Comment by Wyox** [comment]
I just had another look at it and ran it with different configurations.

The following seems to fail the tests:
- macOS 10.15.3 with php 7.4 
- Docker for Mac running a container with php:7.4.3-cli-alpine 
- Docker for Mac running a container with php:7.4.3-fpm-alpine

But with the following configurations it seems to run fine
- Windows 10 running php 7.4 in a Ubuntu 18.04 WSL configuration
- Docker Desktop running a container with php:7.4.3-cli-alpine 

I've updated the repository to include the Dockerfile I used during these tests https://github.com/Wyox/laravel-artisan-test-env/blob/master/docker/php/Dockerfile

macOS 10.15.3 native binary
Screenshot 2020-03-05 at 15 12 51

Docker for Mac php:7.4.3-cli-alpine
Screenshot 2020-03-05 at 15 12 52

Windows 10 with Ubuntu 18.04 

ubuntu-wsl

Windows 10 with Docker Desktop
docker-container

**Comment by Wyox** [comment]
Seems to only happen with macOS or it must be my machine specifically...

I've build the same Docker image on macOS, Windows 10 (WSL) and a Ubuntu 18.04 server and pushed it to a private registry. 

If I build the image on my macOS and pull it on the different machines it seems to fail the tests. However if the build is done on other machines both `phpunit` and `php artisan test` seem to pass. 

I'll investigate if there are any noticeable differences between the images

**Comment by Wyox** [comment]
Issue seems to be reproducible now, the example project didn't include a `.env` file. I think you should see the same error now too.


What is causing the issue:

1. Laravel bootstraps Dotenv
2. Dotenv loads .env and sets any found variable into the `$_SERVER` scope ( see [LoadsEnvironmentVariable](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php) and [Env](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Env.php) )
3. At some point TestCommand calls and runs command with `Symfony\Component\Process\Process`
4. Process collects environment variables before running the command (`getDefaultEnv()` in Process) and merges any variables found in $_SERVER or $_ENV
5. Command gets run with given environment variables

Since phpunit will start with the environment variables found in $_SERVER or $_ENV any environment variables set in phpunit.xml will be ignored.

I've changed the PR to reset any environment variables retrieved from a .env file if the --env option isn't passed before running the command. This should both fix .env.testing not being loaded and any phpunit.xml set variables not being loaded.

**Comment by Wyox** [comment]
Changed phpstan.neon.dist to ignore a incorrect typehint given for a return in vlucas/phpdotenv 4.0.0

**Comment by obennaci** [comment]
Running into as well. Not sure if further explaining is needed.
Basically, I'm using 2 databases, `postgres` and `postgres_testing`, the latter is used in `.env.testing`. Experimented on both Linux and Docker php/alpine:

- `vendor/bin/phpunit`: properly loads `.env.testing` and uses the testing db
- `artisan test`: doesn't load `.env.testing`, therefore uses the "default" db
- `artisan test --env=testing`: properly loads `.env.testing` and uses the testing db

Using this PR, `artisan test` behaves the same as regular `phpunit` command :+1:

**Comment by nunomaduro** [comment]
Just run some tests locally, and indeed! This pull request seems correct! Thanks!

**Pull request merged**
