### PR TITLE
Replace abandoned packages in v3.x

### PR DESCRIPTION
**Pull request by oliworx**
replace abandoned package jakub-onderka/php-console-highlighter with "php-parallel-lint/php-console-highlighter 0.5

closes https://github.com/nunomaduro/collision/issues/172

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]
Was just going to open this PR. Thanks. 👍🏻 LGTM!

**Comment by nunomaduro** [comment]
@owenvoke I had no plans on fixing this on the version 3, since we already on the version 5.

But fell free to merge this, and tag it.

**Comment by nunomaduro** [comment]
@owenvoke Please check if there is no breaking changes at all.

**Comment by owenvoke** [comment]
@nunomaduro, so v3.x isn't maintained anymore? 🤔

Anyway, it appears that v0.5 (which this PR is changing to) is the version before they changed the namespace in the new release. I think this should be fine, but I'll try and do some testing when I get time. Unfortunately, the 3.x branch is still on Travis CI. So we can't really run the tests matrix against it, so manual testing it is... 🤷🏻

**Comment by nunomaduro** [comment]
@owenvoke Personally I think we should not touch in this branch unless is really necessary. Let's keep in this on hold for now...

**Comment by nunomaduro** [comment]
@oliworx Just mentioned `Please consider that Laravel 6 is a LTS release and still used quite a lot.`.

**Comment by nunomaduro** [comment]
@owenvoke @oliworx Any change of migrating the `3.x` to GitHub actions? So we are sure not break things?

**Comment by owenvoke** [comment]
Yeah, I can open a PR with GHA, and then we can rebase this over the top to test it. If that's alright?

This should work, in theory: https://github.com/nunomaduro/collision/pull/174 👍🏻

**Comment by oliworx** [comment]
@owenvoke @nunomaduro What about making v4.x or v5.x available for Laravel 6? That would be even better solution for me.

**Comment by owenvoke** [comment]
@oliworx, do you mind rebasing onto the latest `v3.x` branch so that the CI is run? I'm not sure how feasible it would be to make 4.x/5.x compatible with Laravel 6 🤔

**Comment by oliworx** [comment]
> @oliworx, do you mind rebasing onto the latest `v3.x` branch so that the CI is run? I'm not sure how feasible it would be to make 4.x/5.x compatible with Laravel 6

@owenvoke sure, I did rebase it now

**Comment by nunomaduro** [comment]
If tests are passing, fell free to merge in release a "minor" version.

**Comment by owenvoke** [comment]
@oliworx, v3.2.0 has now been released with these changes. 👍🏻

**Comment by oliworx** [comment]
@owenvoke awesome, thank you :+1:

**Pull request merged**
