### PR TITLE
Return self instead of class names

### PR DESCRIPTION
**Pull request by lex111**
Just a tiny improvement.

### CODE REVIEW

**Comment by Patryk27** [comment]
Annotating the `self` type makes it impossible to overwrite given method (https://ideone.com/h4cVa3).
Maybe doing `@return $this` and not annotating the return type itself would be a better choice?

**Comment by ianrodrigues** [comment]
@Patryk27 That's true

**Comment by nunomaduro** [comment]
@lex111 @Patryk27 @ianrodrigues I believe that the current return type hint is the correct. It says that this method must return a class that implements the contract/interface `\NunoMaduro\Collision\Contracts\Handler`. That basically is the same as `return $this`.

**Comment by nunomaduro** [comment]
I am closing this if is ok to you all.

**Comment by lex111** [comment]
Yes you are all right, I did not consider the problem associated with inheritance, it may not be required, however  do not need to return  `self`.

**Pull request closed without merging**
