### PR TITLE
feat: adds ignition solutions

### PR DESCRIPTION
**Pull request by nunomaduro**
## Want to start contributing to open source? Please keep the work in this pull request!

✨ How to get started:
1. **Fork** the collision repository: clicking on the button `fork` on the very top right of this page
2. **Clone** the repository locally running: `git clone https://github.com/YOUR_GITHUB_USERNAME/collision`
3. **Checkout** in this branch running: `git checkout feat/handle-ignition-solutions`
4.  **Install** Composer by running: `composer install`
5. **Modify the code** while testing it running: `php playground/exception.php`
6. **Update tests** running: `./vendor/bin/phpunit`
6. Once you are done, **commit and push** your code
7. Make a **pull request** against `feat/handle-ignition-solutions`
8. Thank you!

At the moment we have the displayable solutions. And where is the list that needs to be done:

- [ ] Check how collision behaves with multiple solutions
- [ ] Check of collision catch all the solutions provided by ignition
- [ ] Check how collision behaves with multiple links attached with the solution
- [ ] Update `renderEditor` function to apply the new design
- [ ] Update `renderTrace` function to apply the new design

Maybe later:
- [ ] Allow to pass the parameter `--fix` to run the `fix` for the solution
- [ ]  Allow to pass the parameter `--share` to get a `share` thing of ignition
- [ ] Anything else?

Here is the new design:

64347386-c15ef200-cfeb-11e9-856c-2af1c9245c35

### CODE REVIEW

**Comment by nunomaduro** [comment]
closes #67

**Comment by sierrafayad** [comment]
Very detailed how to get started lets add an item between 3 and 4:

3. **Checkout** in this branch running: `git checkout feat/handle-ignition-solutions`
4.  **Install** Composer by running: `composer install`
5.  **Modify the code** while testing it running: `php playground/exception.php`

You can guess what happened while going step by step 😅

**Comment by nunomaduro** [comment]
@sierrafayad Thanks for the info. It's good to have a detailed instructions for newcomers.

**Comment by nunomaduro** [comment]
Done on the `next` branch.

**Pull request closed without merging**
